-- return {
-- 	{
-- 		"robitx/gp.nvim",
-- 		config = function()
-- 			local conf = {
--         openai_api_key = "",
-- 				-- For customization, refer to Install > Configuration in the Documentation/Readme
-- 			}
-- 			require("gp").setup(conf)
-- 
-- 			vim.keymap.set("v", "<C-l>", ":GpRewrite<CR>", {})
-- 		end,
-- 	},
-- }
