require("utils")
require("sets")
require("mappings")

require("./plugins")
require("plugins.flutter")
require("plugins.gitgutter")
require("plugins.lsp")
require("plugins.lualine")
require("plugins.luasnip")
require("plugins.noirbuddy")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.undotree")
require("plugins.harpoon")
require("plugins.neorg")

require("utils")
require("utils.autocommands")
require("utils.cpp")
require("utils.dart")

require("others.job_runner")
