-- AUTO-GENERATED by LayoutRR.save() -- do not edit by hand.
-- Knobs live in layout-overrides.lua. Previous version: <this file>.bak
return {
  version = 2,
  monitors = {
    { name = "DP-1", active = "5", special = "special:scratchpad2", focused = true },
    { name = "HDMI-A-1", active = "2", special = nil, focused = false },
  },
  focused = 11,
  windows = {
    { class = "google-chrome", ws = "1", mon = "DP-1", floating = false, pinned = false, fullscreen = 0, x = 2563, y = 30, w = 2554, h = 1407, initial_class = "google-chrome" },
    { class = "google-chrome", ws = "2", mon = "HDMI-A-1", floating = false, pinned = false, fullscreen = 0, x = 3, y = 30, w = 2554, h = 1407, initial_class = "google-chrome" },
    { class = "steam", ws = "3", mon = "DP-1", floating = true, pinned = false, fullscreen = 0, x = 3290, y = 384, w = 1100, h = 700, initial_class = "steam" },
    { class = "steam", ws = "3", mon = "DP-1", floating = true, pinned = false, fullscreen = 0, x = 3369, y = 181, w = 942, h = 1106, initial_class = "steam" },
    { class = "discord", ws = "4", mon = "DP-1", floating = false, pinned = false, fullscreen = 0, x = 2563, y = 30, w = 1274, h = 1407, initial_class = "discord" },
    { class = "google-chrome", ws = "4", mon = "DP-1", floating = false, pinned = false, fullscreen = 0, x = 3843, y = 30, w = 1274, h = 1407, initial_class = "google-chrome" },
    { class = "org.telegram.desktop", ws = "5", mon = "DP-1", floating = false, pinned = false, fullscreen = 0, x = 2563, y = 30, w = 1300, h = 1407, initial_class = "org.telegram.desktop" },
    { class = "chrome-web.whatsapp.com__-Default", ws = "5", mon = "DP-1", floating = false, pinned = false, fullscreen = 0, x = 3869, y = 30, w = 1248, h = 1407, initial_class = "chrome-web.whatsapp.com__-Default" },
    { class = "com.mitchellh.ghostty", ws = "special:scratchpad", mon = "DP-1", floating = false, pinned = false, fullscreen = 0, x = 2563, y = 30, w = 1399, h = 1407, initial_class = "com.mitchellh.ghostty" },
    { class = "org.omarchy.agent", ws = "special:scratchpad", mon = "DP-1", floating = false, pinned = false, fullscreen = 0, x = 3968, y = 30, w = 1149, h = 1407, initial_class = "org.omarchy.agent" },
    { class = "chatgpt", ws = "special:scratchpad2", mon = "DP-1", floating = false, pinned = false, fullscreen = 0, x = 2563, y = 30, w = 2554, h = 1407, initial_class = "chatgpt" },
  },
}
