-- AUTO-GENERATED by LayoutRR.save() -- do not edit by hand.
-- Splash-screen apps (Steam/Discord) are placed by a static rule because
-- they map a loader window first, which defeats timing-based placement.
-- Anchored class match, so Steam *games* are unaffected.

o.window("^(steam)$", { workspace = "special:scratch1 silent" })
