-- Window layout save/restore, compositor-side (replaces the bash
-- layout-save/layout-boot pair). Geometry is read from live window handles
-- and restore verifies sizes with a measure-and-correct loop, so restored
-- dimensions actually match the save.
--
--   LayoutRR.save()     snapshot every mapped window -> layout-data.lua,
--                       regenerate splash-app rules -> layout-rules.lua
--   LayoutRR.restore()  relaunch + replace everything (runs on boot)
--
-- CLI wrappers (~/.local/bin/layout-save, layout-boot) call these through
-- `hyprctl dispatch`. Keybind: CTRL+ALT+L -> save (see bindings.lua).

local HOME = os.getenv("HOME") or ""
local SPEC = HOME .. "/.config/hypr/layout-data.lua"
local RULES = HOME .. "/.config/hypr/layout-rules.lua"
local TIMEOUT_MS = 60000 -- per-window wait
local POLL_MS = 250
local SPLASHY = { steam = true, discord = true } -- placed by static rules

-- Which URL each google-chrome "slot" (workspace) opens on restore. Edit to
-- taste; a workspace with no entry opens a blank window.
local CHROME_URLS = {
  ["2"] = "https://youtube.com",
  ["special:scratchpad"] = "https://claude.ai/code",
  ["special:scratch2"] = "https://mail.google.com",
}

LayoutRR = LayoutRR or {}

local function notify(urgency, msg)
  hl.exec_cmd("notify-send -u " .. urgency .. " layout " .. o.shell_quote(msg))
end

local function vec(v)
  if type(v) ~= "table" then return 0, 0 end
  return math.floor(v.x or v[1] or 0), math.floor(v.y or v[2] or 0)
end

local function after(ms, fn)
  hl.timer(function()
    local ok, err = pcall(fn)
    if not ok then notify("critical", "layout error: " .. tostring(err)) end
  end, { timeout = ms, type = "oneshot" })
end

local function file_exists(path)
  local f = io.open(path, "r")
  if f then f:close() end
  return f ~= nil
end

-- ---------------------------------------------------------------- save ----

function LayoutRR.save()
  local rows = {}
  for _, w in ipairs(hl.get_windows()) do
    if w.mapped and w.workspace and w.workspace.name ~= "" then
      local x, y = vec(w.at)
      local sw, sh = vec(w.size)
      rows[#rows + 1] = {
        class = w.class,
        ws = w.workspace.name,
        mon = w.monitor and w.monitor.name or "",
        floating = w.floating and true or false,
        x = x, y = y, w = sw, h = sh,
      }
    end
  end
  table.sort(rows, function(a, b)
    if a.ws ~= b.ws then return a.ws < b.ws end
    if a.x ~= b.x then return a.x < b.x end
    return a.y < b.y
  end)

  local f = io.open(SPEC, "w")
  if not f then return notify("critical", "cannot write " .. SPEC) end
  f:write("-- AUTO-GENERATED by LayoutRR.save() -- do not edit by hand.\nreturn {\n")
  for _, r in ipairs(rows) do
    f:write(string.format(
      "  { class = %q, ws = %q, mon = %q, floating = %s, x = %d, y = %d, w = %d, h = %d },\n",
      r.class, r.ws, r.mon, tostring(r.floating), r.x, r.y, r.w, r.h))
  end
  f:write("}\n")
  f:close()

  local rf = io.open(RULES, "w")
  if rf then
    rf:write("-- AUTO-GENERATED by LayoutRR.save() -- do not edit by hand.\n")
    rf:write("-- Splash-screen apps (Steam/Discord) are placed by a static rule because\n")
    rf:write("-- they map a loader window first, which defeats timing-based placement.\n")
    rf:write("-- Anchored class match, so Steam *games* are unaffected.\n\n")
    for _, r in ipairs(rows) do
      if SPLASHY[r.class] then
        rf:write(string.format('o.window("^(%s)$", { workspace = %q })\n', r.class, r.ws .. " silent"))
        if r.floating then
          rf:write(string.format('o.window("^(%s)$", { float = true, size = "%d %d" })\n', r.class, r.w, r.h))
        end
      end
    end
    rf:close()
  end

  notify("low", "saved " .. #rows .. " windows")
end

-- ------------------------------------------------------------- restore ----

local function resolve_cmd(class)
  local fixed = {
    ["com.mitchellh.ghostty"] = "ghostty",
    ["org.telegram.desktop"] = "telegram-desktop",
    ["chrome-web.whatsapp.com__-Default"] = "omarchy-launch-webapp https://web.whatsapp.com/",
    ["chromium"] = "chromium --new-window",
  }
  if fixed[class] then return fixed[class] end
  local domain = class:match("^chrome%-web%.(.+)__%-Default$")
  if domain then return "omarchy-launch-webapp https://" .. domain .. "/" end
  if file_exists(HOME .. "/.local/share/applications/" .. class .. ".desktop")
      or file_exists("/usr/share/applications/" .. class .. ".desktop") then
    return "gtk-launch " .. class
  end
  return class
end

-- orientation of B vs A from saved/actual corners: H (side-by-side) or V
local function orient(ax, ay, bx, by)
  return math.abs(bx - ax) >= math.abs(by - ay) and "H" or "V"
end

function LayoutRR.restore(opts)
  opts = opts or {}

  local ok, spec = pcall(dofile, SPEC)
  if not ok or type(spec) ~= "table" or #spec == 0 then
    return notify("critical", "no layout saved (" .. SPEC .. ")")
  end

  if not opts.force then
    for _, w in ipairs(hl.get_windows()) do
      if w.class == "google-chrome" or w.class:lower():match("chromium") then
        return notify("normal", "browser already open; skipping restore")
      end
    end
  end

  -- group rows per workspace: normal workspaces first, then specials
  local order, by_ws = {}, {}
  for _, r in ipairs(spec) do
    if not SPLASHY[r.class] then
      if not by_ws[r.ws] then
        by_ws[r.ws] = {}
        order[#order + 1] = r.ws
      end
      table.insert(by_ws[r.ws], r)
    end
  end
  table.sort(order, function(a, b)
    local sa = a:match("^special:") and 1 or 0
    local sb = b:match("^special:") and 1 or 0
    if sa ~= sb then return sa < sb end
    return a < b
  end)

  -- launch every non-browser app up front; browsers launch one at a time
  -- while placing so their windows can't be confused with each other.
  for _, r in ipairs(spec) do
    if not SPLASHY[r.class] and r.class ~= "google-chrome" then
      hl.exec_cmd(resolve_cmd(r.class))
    end
  end

  local placed = {} -- [address] = true
  local known_chrome = {}
  for _, w in ipairs(hl.get_windows()) do
    if w.class == "google-chrome" then known_chrome[w.address] = true end
  end

  local function find_window(row)
    for _, w in ipairs(hl.get_windows()) do
      if w.mapped and not placed[w.address] then
        if row.class == "google-chrome" then
          if w.class == "google-chrome" and not known_chrome[w.address] then return w end
        elseif w.class == row.class then
          return w
        end
      end
    end
  end

  -- open (or ensure visible) a workspace on its monitor
  local function show_ws(ws, mon)
    if mon and mon ~= "" then hl.dispatch(hl.dsp.focus({ monitor = mon })) end
    local name = ws:match("^special:(.+)$")
    if name then
      local m = mon and mon ~= "" and hl.get_monitor(mon) or hl.get_active_monitor()
      local active = m and m.active_special_workspace
      if not (active and active.name == ws) then
        hl.dispatch(hl.dsp.workspace.toggle_special(name))
      end
    else
      hl.dispatch(hl.dsp.focus({ workspace = ws }))
    end
  end

  local function hide_special(ws, mon)
    local name = ws:match("^special:(.+)$")
    if not name then return end
    local m = mon and mon ~= "" and hl.get_monitor(mon) or hl.get_active_monitor()
    local active = m and m.active_special_workspace
    if active and active.name == ws then
      hl.dispatch(hl.dsp.workspace.toggle_special(name))
    end
  end

  -- measure-and-correct sizing: read actual size, resize, re-check. This is
  -- what the old two-blind-passes version couldn't do.
  local function resize_pass(rows, pass, done)
    local dirty = false
    for _, r in ipairs(rows) do
      if r._addr and not r.floating then
        local w = hl.get_window("address:" .. r._addr)
        if w then
          local cw, ch = vec(w.size)
          if math.abs(cw - r.w) > 2 or math.abs(ch - r.h) > 2 then
            hl.dispatch(hl.dsp.window.resize({ x = r.w, y = r.h, relative = false, window = w }))
            dirty = true
          end
        end
      end
    end
    if dirty and pass < 8 then
      after(150, function() resize_pass(rows, pass + 1, done) end)
    else
      done()
    end
  end

  -- place rows[i] into ws, sequentially, waiting for each window to appear
  local function place_rows(ws, rows, i, deadline, done)
    if i > #rows then
      after(120, function() resize_pass(rows, 1, done) end)
      return
    end
    local r = rows[i]
    if r.class == "google-chrome" and not r._launched then
      r._launched = true
      hl.exec_cmd("google-chrome-stable --new-window " .. (CHROME_URLS[ws] or ""))
    end
    local w = find_window(r)
    if not w then
      if deadline <= 0 then
        notify("critical", "timed out waiting for " .. r.class)
        place_rows(ws, rows, i + 1, TIMEOUT_MS, done)
      else
        after(POLL_MS, function() place_rows(ws, rows, i, deadline - POLL_MS, done) end)
      end
      return
    end

    placed[w.address] = true
    if r.class == "google-chrome" then known_chrome[w.address] = true end
    r._addr = w.address

    -- move-and-follow so this window splits the previously placed one
    hl.dispatch(hl.dsp.window.move({ workspace = ws, window = w }))

    if r.floating then
      hl.dispatch(hl.dsp.window.move({ x = r.x, y = r.y, relative = false, window = w }))
      hl.dispatch(hl.dsp.window.resize({ x = r.w, y = r.h, relative = false, window = w }))
      place_rows(ws, rows, i + 1, TIMEOUT_MS, done)
      return
    end

    -- dwindle picks split orientation from aspect; flip when it disagrees
    -- with the saved arrangement, then continue.
    local prev
    for k = i - 1, 1, -1 do
      if rows[k]._addr and not rows[k].floating then prev = rows[k]; break end
    end
    if not prev then
      place_rows(ws, rows, i + 1, TIMEOUT_MS, done)
      return
    end
    after(100, function()
      local pw = hl.get_window("address:" .. prev._addr)
      local cw = hl.get_window("address:" .. r._addr)
      if pw and cw then
        local pax, pay = vec(pw.at)
        local cax, cay = vec(cw.at)
        local want = orient(prev.x, prev.y, r.x, r.y)
        local have = orient(pax, pay, cax, cay)
        if want ~= have then
          hl.dispatch(hl.dsp.focus({ window = cw }))
          hl.dispatch(hl.dsp.layout("togglesplit"))
        end
      end
      place_rows(ws, rows, i + 1, TIMEOUT_MS, done)
    end)
  end

  -- run workspaces sequentially
  local function run_ws(idx)
    if idx > #order then
      -- land on the first normal workspace
      local first = nil
      for _, ws in ipairs(order) do
        if not ws:match("^special:") then first = ws; break end
      end
      if first then
        local mon = by_ws[first][1].mon
        if mon ~= "" then hl.dispatch(hl.dsp.focus({ monitor = mon })) end
        hl.dispatch(hl.dsp.focus({ workspace = first }))
      end
      notify("low", "layout restored")
      return
    end
    local ws = order[idx]
    local rows = by_ws[ws]
    local mon = rows[1].mon
    show_ws(ws, mon)
    after(80, function()
      place_rows(ws, rows, 1, TIMEOUT_MS, function()
        hide_special(ws, mon)
        run_ws(idx + 1)
      end)
    end)
  end

  run_ws(1)
end

-- Restore the boot layout once the session is up (replaces the old
-- `exec-once = sleep 3 && layout-boot`).
hl.on("hyprland.start", function()
  after(3000, function() LayoutRR.restore({ boot = true }) end)
end)
