-- AUTO-GENERATED by LayoutRR.save() -- do not edit by hand.
return {
  { class = "google-chrome", ws = "1", mon = "DP-1", floating = false, x = 2563, y = 29, w = 2554, h = 1408 },
  { class = "com.stremio.stremio", ws = "2", mon = "HDMI-A-1", floating = false, x = 3, y = 29, w = 1274, h = 1408 },
  { class = "google-chrome", ws = "2", mon = "HDMI-A-1", floating = false, x = 1283, y = 29, w = 1274, h = 1408 },
  { class = "steam", ws = "special:scratch1", mon = "DP-1", floating = false, x = 2563, y = 29, w = 2554, h = 1408 },
  { class = "google-chrome", ws = "special:scratch2", mon = "DP-1", floating = false, x = 2563, y = 29, w = 1274, h = 1408 },
  { class = "com.mitchellh.ghostty", ws = "special:scratch2", mon = "DP-1", floating = false, x = 3843, y = 29, w = 1274, h = 701 },
  { class = "com.mitchellh.ghostty", ws = "special:scratch2", mon = "DP-1", floating = false, x = 3843, y = 736, w = 634, h = 701 },
  { class = "com.mitchellh.ghostty", ws = "special:scratch2", mon = "DP-1", floating = false, x = 4483, y = 736, w = 634, h = 701 },
  { class = "chrome-web.whatsapp.com__-Default", ws = "special:scratch3", mon = "DP-1", floating = false, x = 2563, y = 29, w = 1274, h = 1408 },
  { class = "org.telegram.desktop", ws = "special:scratch3", mon = "DP-1", floating = false, x = 3843, y = 29, w = 1274, h = 1408 },
  { class = "localsend", ws = "special:scratch4", mon = "DP-1", floating = true, x = 3216, y = 29, w = 1248, h = 1408 },
}
