-- AUTO-GENERATED by LayoutRR.save() -- do not edit by hand.
-- Splash-screen apps (see `splashy` in layout-overrides.lua) are placed by a
-- static rule because they map a loader window first, which defeats
-- timing-based placement. Anchored class match, so Steam *games* are unaffected.

o.window("^(steam)$", { workspace = "special:scratch1 silent" })
o.window("^(steam)$", { float = true, size = "1100 700" })
o.window("^(discord)$", { workspace = "special:scratch4 silent" })
