-- AUTO-GENERATED by LayoutRR.save() -- do not edit by hand.
-- Knobs live in layout-overrides.lua. Previous version: <this file>.bak
return {
  version = 2,
  monitors = {
    { name = "DP-1", active = "1", special = nil, focused = true },
    { name = "HDMI-A-1", active = "2", special = nil, focused = false },
  },
  focused = 1,
  windows = {
    { class = "google-chrome", ws = "1", mon = "DP-1", floating = false, pinned = false, fullscreen = 1, x = 2564, y = 30, w = 2552, h = 1406, initial_class = "google-chrome" },
    { class = "com.stremio.stremio", ws = "2", mon = "HDMI-A-1", floating = false, pinned = false, fullscreen = 0, x = 4, y = 30, w = 1272, h = 1406, initial_class = "com.stremio.stremio" },
    { class = "google-chrome", ws = "2", mon = "HDMI-A-1", floating = false, pinned = false, fullscreen = 0, x = 1284, y = 30, w = 1272, h = 1406, initial_class = "google-chrome" },
    { class = "steam", ws = "special:scratch1", mon = "DP-1", floating = true, pinned = false, fullscreen = 0, x = 3290, y = 383, w = 1100, h = 700, initial_class = "steam" },
    { class = "org.localsend.localsend_app", ws = "special:scratch3", mon = "DP-1", floating = false, pinned = false, fullscreen = 0, x = 2564, y = 30, w = 1272, h = 1406, initial_class = "org.localsend.localsend_app" },
    { class = "org.gnome.Nautilus", ws = "special:scratch3", mon = "DP-1", floating = false, pinned = false, fullscreen = 0, x = 3844, y = 30, w = 1272, h = 1406, initial_class = "org.gnome.Nautilus" },
    { class = "discord", ws = "special:scratch4", mon = "DP-1", floating = false, pinned = false, fullscreen = 0, x = 2564, y = 30, w = 1272, h = 1406, initial_class = "discord" },
    { class = "org.telegram.desktop", ws = "special:scratch4", mon = "DP-1", floating = false, pinned = false, fullscreen = 0, x = 3844, y = 30, w = 1272, h = 699, initial_class = "org.telegram.desktop" },
    { class = "chrome-web.whatsapp.com__-Default", ws = "special:scratch4", mon = "DP-1", floating = false, pinned = false, fullscreen = 0, x = 3844, y = 737, w = 1272, h = 699, initial_class = "chrome-web.whatsapp.com__-Default" },
    { class = "com.mitchellh.ghostty", ws = "special:scratchpad", mon = "DP-1", floating = false, pinned = false, fullscreen = 0, x = 2564, y = 30, w = 2552, h = 1406, initial_class = "com.mitchellh.ghostty" },
  },
}
